FROM ubuntu:22.04
WORKDIR ingestion-service/src/
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ARG INGESTION-SERVICE-URL="http://localhost:8001/ingestion/"
ARG MODEL-SERVICE-URL="http://localhost:8002/model/"
EXPOSE 8003
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003"]