FROM ubuntu:22.04
WORKDIR ingestion-service/src/
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ARG INGESTION-SERVICE-URL="http://localhost:8001/model/"
ARG MONITORING-SERVICE-URL="http://localhost:8003/monitor/"
EXPOSE 8002
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]