FROM python:3.11-slim
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
WORKDIR src/ingestion-service/src
ARG MODEL-SERVICE-URL="http://localhost:8002/model/"
ARG MONITORING-SERVICE-URL="http://localhost:8003/monitor/"
EXPOSE 8001
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]